### ISSUE TITLE
SPIPED: Does not build in OpenWRT 19.07.3

### ISSUE THREAD

**Issue by wicadmin** [InkblotAdmirer/custom_feed#1]
Hi, I am getting a POSIX error.

However, can you update this to spiped 1.6.1

```
if [ -e libcperciva/cpusupport/Build/cpusupport.sh ];	\
then								\
	( export CC="x86_64-openwrt-linux-musl-gcc"; command -p sh 			\
	    libcperciva/cpusupport/Build/cpusupport.sh	\
	    "$PATH" ) > cpusupport-config.h;			\
else								\
	: > cpusupport-config.h;				\
fi
Checking if compiler supports X86 CPUID feature... yes
Checking if compiler supports X86 AESNI feature... yes, via -maes
Checking if compiler supports X86 RDRAND feature... yes, via -mrdrnd
CFLAGS="${CFLAGS:--O2}";	export CFLAGS; \
LDADD_POSIX=`export CC=\"x86_64-openwrt-linux-musl-gcc\"; cd libcperciva/POSIX && command -p sh posix-l.sh \"$PATH\"`;	\
CFLAGS_POSIX=`export CC=\"x86_64-openwrt-linux-musl-gcc\"; cd libcperciva/POSIX && command -p sh posix-cflags.sh \"$PATH\"`;	\
. ./cpusupport-config.h;			\
for D in spiped spipe tests/dnsthread-resolve tests/nc-client tests/nc-server	 tests/valgrind; do			\
	( cd ${D} && make all ) || exit 2;	\
done
WARNING: POSIX violation: /usr/bin/env bash's command -p resets $PATH
WARNING: POSIX violation: make's CC doesn't understand -lrt
posix-l.sh: 24: posix-l.sh: rm: not found
WARNING: POSIX violation: make's CC doesn't understand -lxnet
posix-l.sh: 24: posix-l.sh: rm: not found
Makefile:14: recipe for target 'all' failed
make[3]: *** [all] Error 127
make[3]: Leaving directory '/home/build/build_dir/build_dir/target-x86_64_musl/spiped-2018-05-24'
Makefile:60: recipe for target '/home/build/build_dir/build_dir/target-x86_64_musl/spiped-2018-05-24/.built' failed
make[2]: *** [/home/build/build_dir/build_dir/target-x86_64_musl/spiped-2018-05-24/.built] Error 2
make[2]: Leaving directory '/home/build/openwrt_packages/net/spiped'
time: package/feeds/packages/spiped/compile#0.81#0.22#2.07
package/Makefile:111: recipe for target 'package/feeds/packages/spiped/compile' failed
make[1]: *** [package/feeds/packages/spiped/compile] Error 2
make[1]: Leaving directory '/home/build/build_dir'
/home/build/build_dir/include/toplevel.mk:218: recipe for target 'package/spiped/compile' failed
make: *** [package/spiped/compile] Error 2

```

**Comment by InkblotAdmirer** [comment]
The script being run at that point executes an "rm -f a.out" and based on your output it looks like it can't find the rm command?  rm -f should produce no errors if a.out isn't found.

Try executing "rm -f <some random non-existent file name> and compare the output, or "which rm" to find the location of rm.

If you want to see if you can build further, enter build_dir/target.../spiped-<version>/libcperciva/POSIX and edit posix-l.sh:  remove line 24, the rm -f a.out.  Then go back to your source folder and make/package/spiped V=s  (don't clean or it will re-extract the archive and revert to the original code).  If you get past this point you need to figure out why the script can't find the rm command -- are you compiling from a jail, for example?

As to the version, I didn't see that a newer release had been tagged.  I will update after building and testing.

**Comment by wicadmin** [comment]
I use openwrt-vivarium for my custom builds. Will need to check about `rm` being missing. 

Here is the new version:
https://github.com/Tarsnap/spiped/releases

**Comment by InkblotAdmirer** [comment]
I upgraded to 1.6.1 and tested against a non-upgraded router, and it is (not unexpectedly) backwards compatible.  It also looks like the POSIX checking has changed quite a bit and I don't get the warnings associated with the file causing you problems -- you may be in luck and the new version may build without issues in your container.

**Comment by wicadmin** [comment]
awesome....i'll give it a try and let you know.

**Comment by wicadmin** [comment]
Alright...it built the spiped package without issues.

I'll now make my image and fully test.

Thank you very much for the quick turnaround!
